# Generated by Django 3.2.8 on 2021-11-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(default='61544', max_length=6)),
                ('money', models.IntegerField(default=100000000)),
                ('history', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
