# Generated by Django 3.2.8 on 2021-11-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_participant_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='group',
            field=models.CharField(default=':', max_length=1),
        ),
    ]
