# Generated by Django 3.2.8 on 2021-11-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_participant_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='time_second',
            field=models.IntegerField(default=0),
        ),
    ]
