# Generated by Django 3.2.8 on 2021-11-07 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_participant_time_second'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flow_Data',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='time_second',
        ),
    ]
