# Generated by Django 3.2.8 on 2021-11-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20211107_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='money',
        ),
    ]
