# Generated by Django 3.2.8 on 2021-11-15 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_remove_participant_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='tip',
            field=models.CharField(default=':', max_length=200),
        ),
    ]
